/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (5.0.1).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package org.openapitools.api;

import org.openapitools.model.Product;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2021-02-12T09:59:57.847217-05:00[America/New_York]")
@Validated
@Api(value = "product", description = "the product API")
public interface ProductApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * POST /product : Add a product
     *
     * @param product Product to add to the store (required)
     * @return Successfully created product (status code 200)
     *         or Invalid input (status code 405)
     */
    @ApiOperation(value = "Add a product", nickname = "addProduct", notes = "", response = Product.class, tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully created product", response = Product.class),
        @ApiResponse(code = 405, message = "Invalid input") })
    @PostMapping(
        value = "/product",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Product> addProduct(@ApiParam(value = "Product to add to the store" ,required=true )  @Valid @RequestBody Product product) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"category_id\" : 6, \"image_url\" : \"image_url\", \"price\" : 1, \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /product/{productId} : Delete a product
     *
     * @param productId ID of product to delete (required)
     * @return Invalid product value (status code 400)
     */
    @ApiOperation(value = "Delete a product", nickname = "deleteProduct", notes = "", tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid product value") })
    @DeleteMapping(
        value = "/product/{productId}"
    )
    default ResponseEntity<Void> deleteProduct(@ApiParam(value = "ID of product to delete",required=true) @PathVariable("productId") Long productId) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /product/{productId} : Return a single product
     *
     * @param productId ID of product to return (required)
     * @return A JSON representation of a product (status code 200)
     *         or Invalid product ID (status code 400)
     *         or Product not found (status code 404)
     */
    @ApiOperation(value = "Return a single product", nickname = "getProductById", notes = "", response = Product.class, tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "A JSON representation of a product", response = Product.class),
        @ApiResponse(code = 400, message = "Invalid product ID"),
        @ApiResponse(code = 404, message = "Product not found") })
    @GetMapping(
        value = "/product/{productId}",
        produces = { "application/json" }
    )
    default ResponseEntity<Product> getProductById(@ApiParam(value = "ID of product to return",required=true) @PathVariable("productId") Long productId) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"category_id\" : 6, \"image_url\" : \"image_url\", \"price\" : 1, \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /product : Update a product
     *
     * @param product Product to add to the store (required)
     * @return Successfully updated product (status code 200)
     *         or Invalid ID supplied (status code 400)
     *         or Product not found (status code 404)
     *         or Invalid input (status code 405)
     */
    @ApiOperation(value = "Update a product", nickname = "updateProduct", notes = "", response = Product.class, tags={ "product", })
    @ApiResponses(value = { 
        @ApiResponse(code = 200, message = "Successfully updated product", response = Product.class),
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Product not found"),
        @ApiResponse(code = 405, message = "Invalid input") })
    @PutMapping(
        value = "/product",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    default ResponseEntity<Product> updateProduct(@ApiParam(value = "Product to add to the store" ,required=true )  @Valid @RequestBody Product product) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"category_id\" : 6, \"image_url\" : \"image_url\", \"price\" : 1, \"name\" : \"name\", \"description\" : \"description\", \"id\" : 0 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
